status_def = [  
    "Blind",
    "Zombie",
    "Poison",
    "Magitek",
    "Clear",
    "Pig",
    "Petrify",
    "KO'd",
    "Condemned",
    "Near fatal",
    "Image",
    "Silence",
    "Berserk",
    "Confuse",
    "Seizure",
    "Psyche",
    "Dance",
    "Regen",
    "Slow",
    "Haste",
    "Stop",
    "Shell",
    "Protect",
    "Reflect",
    "True knight",
    "Runic",
    "Reraise",
    "Morph",
    "Chant",
    "Hidden",
    "Ace",
    "float"]

status_mons_def = [
    "Blind",
    "Zombie",
    "Poison",
    "Magitek",
    "Clear",
    "Pig",
    "Petrify",
    "KO'd",
    "Condemned",
    "Near fatal",
    "Image",
    "Silence",
    "Berserk",
    "Confuse",
    "Seizure",
    "Psyche",
    "Float",
    "Regen",
    "Slow",
    "Haste",
    "Stop",
    "Shell",
    "Protect",
    "Reflect",
    "True knight",
    "Runic",
    "Reraise",
    "Morph",
    "Chant",
    "Hidden",
    "Ace",
    "Removable float"]